In [17]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler

pd.pandas.set_option('display.max_columns', None)

In [18]:
data = pd.read_csv('train.csv')

print(data.shape)

data.head()

(159256, 24)

,id,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,relaxation,fasting blood sugar,Cholesterol,triglyceride,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,dental caries,smoking
0,0,55,165,60,81.0,0.5,0.6,1,1,135,87,94,172,300,40,75,16.5,1,1.0,22,25,27,0,1
1,1,70,165,65,89.0,0.6,0.7,2,2,146,83,147,194,55,57,126,16.2,1,1.1,27,23,37,1,0
2,2,20,170,75,81.0,0.4,0.5,1,1,118,75,79,178,197,45,93,17.4,1,0.8,27,31,53,0,1
3,3,35,180,95,105.0,1.5,1.2,1,1,131,88,91,180,203,38,102,15.9,1,1.0,20,27,30,1,0
4,4,30,165,60,80.5,1.5,1.0,1,1,121,76,91,155,87,44,93,15.4,1,0.8,19,13,17,0,1

In [19]:
x_train, x_test, y_train, y_test = train_test_split(data, data.smoking, random_state=0, test_size=0.1)

In [20]:
x_train

,id,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,relaxation,fasting blood sugar,Cholesterol,triglyceride,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,dental caries,smoking
98790,98790,50,155,50,72.0,0.9,0.1,1,1,118,76,96,220,115,80,117,13.0,1,0.7,21,15,15,0,0
83190,83190,50,155,65,79.0,1.5,1.0,1,1,116,72,103,205,147,54,122,13.5,1,0.9,22,20,18,0,0
136389,136389,45,175,75,92.0,0.1,0.1,1,1,124,73,92,203,253,34,119,15.8,1,1.0,25,38,76,0,1
126946,126946,55,155,60,77.0,0.4,0.4,1,1,125,76,89,196,36,74,115,14.1,1,0.7,33,20,26,0,0
148686,148686,40,165,70,85.0,1.5,1.2,1,1,114,64,93,155,166,33,90,15.5,1,1.0,23,32,29,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97639,97639,45,150,55,85.0,0.6,0.9,1,1,102,68,90,180,45,61,109,12.0,1,1.0,19,14,24,0,0
95939,95939,40,160,60,70.1,1.5,1.2,1,1,109,72,85,167,44,65,93,13.0,1,0.9,20,18,19,0,0
152315,152315,40,155,50,68.0,0.8,0.7,1,1,94,68,119,185,65,66,106,11.7,1,0.9,23,27,16,1,0
117952,117952,40,155,70,84.0,0.6,0.4,1,1,110,60,84,177,43,71,96,13.4,1,0.7,16,15,8,0,0
43567,43567,40,170,75,87.0,1.2,1.2,1,1,124,89,112,196,194,41,116,16.0,1,0.9,20,22,52,0,1

In [21]:
train_vars = [var for var in x_train.columns if var not in ['id', 'smoking']]

len(train_vars)

22

In [5]:
# def analyze_continous(df, var): 
#     df = df.copy()

#     if 0 in df[var].unique():
#         pass

#     else: 
#         df[var] = np.log(df[var])
#         if (df[var] > 0).all():
#             df[var] = np.log(df[var])
#         else: 
#             pass

# for var in train_vars: 
#     x_train[var] = analyze_continous(x_train, var)
#     x_test[var] = analyze_continous(x_test, var)

In [22]:
x_train[['id', 'smoking']].reset_index(drop = True)

            id  smoking
0        98790        0
1        83190        0
2       136389        1
3       126946        0
4       148686        1
...        ...      ...
143325   97639        0
143326   95939        0
143327  152315        0
143328  117952        0
143329   43567        1

[143330 rows x 2 columns]

In [23]:
scaler = MinMaxScaler()
scaler.fit(x_train[train_vars])

x_train = pd.concat([x_train[['id', 'smoking']].reset_index(drop=True), 
                     pd.DataFrame(scaler.transform(x_train[train_vars]), columns=train_vars)], 
                     axis = 1)

x_test = pd.concat([x_test[['id', 'smoking']].reset_index(drop = True), 
                     pd.DataFrame(scaler.transform(x_test[train_vars]), columns=train_vars)], 
                     axis = 1)

In [24]:
x_train.to_csv('xtrain.csv', index= False)
x_test.to_csv('xtest.csv', index= False)